name: dart_intro
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/rashakanakri/dart-intro-008

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
   emojis: ^0.9.9
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
